### PR TITLE
Fix test and now inference is compatible with old weights

### PR DESCRIPTION
**Pull request by yujincheng08**
I also try to fix the test code, so it should be carefully merged.

And I modified the inference so that it can now be compatible with the old weight files. But since opencv uses BGR channel order, the performance might be influenced.

### CODE REVIEW

**Comment by cardwing** [comment]
@yujincheng08, thanks for your contribution. However, the current code can already read old weight files and fulfill the requirement of testing.

**Comment by yujincheng08** [comment]
@cardwing Good! So I can close this PR now.

**Comment by yujincheng08** [comment]
@cardwing Oh btw, I found that I didn't commit the change on the train label process function.
See: https://github.com/cardwing/Codes-for-Lane-Detection/blob/master/SCNN-Tensorflow/lane-detection-model/data_provider/lanenet_data_processor.py#L53

It should use NN ranther than BICUBIC for resizing.

**Comment by cardwing** [comment]
@yujincheng08, got it!

**Pull request merged**
